### ISSUE TITLE
Create setup.py file for pip

### ISSUE THREAD

**Issue by Xender** [adamlwgriffiths/OMGL#1]
Hi.

Is OMGL currently usable?
How about creating setup.py file so that the library can be installed from git by pip?
Unfortunately, I have no experience at all with writing setup.py files, so I'm not sure if I can help with that.

And if it's realease-quality, how about submitting it to PyPI?

**Comment by adamlwgriffiths** [comment]
It has some functionality, (buffers, textures, VAO, shader programs) but it's not complete.
I haven't got any documentation or any library support yet, but this is what PyGLy has become essentially.
I'll try and take time to do a setup.py, it's basically a copy/paste job.

**Comment by adamlwgriffiths** [comment]
Just to clarify, what is present in OMGL works, and works quite well. It nicely abstracts away OpenGL wrangling and lets you get on with the job. But there are other features like frame buffer render targets, and better textures that i'd like to support.

**Comment by adamlwgriffiths** [comment]
Done in commit 798137fd3869c5131a30238d4b1e1b010193b3e0

Added setup.py.
Added optional dependencies.
Added requirements files for each group of optional dependencies.
Added version.py.
Uploaded to pypi as `omgl`.
Tagged as 0.0.1.
